INSERT INTO ADDRESS (CITY, STREET_NAME, POST_CODE) VALUES ('Warszawa', 'Waryńskiego', '20-000');
INSERT INTO ADDRESS (CITY, STREET_NAME, POST_CODE) VALUES ('Poznan', 'Pomorska', '20-001');
INSERT INTO ADDRESS (CITY, STREET_NAME, POST_CODE) VALUES ('Wroclaw', 'Kubusia Puchatka', '02-200');
INSERT INTO ADDRESS (CITY, STREET_NAME, POST_CODE) VALUES ('Lublin', 'Tygryska', '03-321');
INSERT INTO ADDRESS (CITY, STREET_NAME, POST_CODE,ID) VALUES ('Łudz', 'Prosiaczka', '04-123',1);