INSERT INTO DOGS (NAME, DOG_BREEDS) VALUES ('Azor', 'Spaniel');
INSERT INTO DOGS (NAME, DOG_BREEDS) VALUES ('Reksio', 'Terrier');
INSERT INTO DOGS (NAME, DOG_BREEDS) VALUES ('Burek', 'Bulldog');
INSERT INTO DOGS (NAME, DOG_BREEDS) VALUES ('Łatka', 'Dalmatynczyk');
INSERT INTO DOGS (NAME, DOG_BREEDS) VALUES ('Mord', 'Mops');